# .github/workflows/install-windows-service.yml
name: My Workflow


on:
  workflow_dispatch:

jobs:
  activate conda:
    name: Activate Conda Environment
    runs-on: self-hosted

    steps:
      - name: Check out Repository
        uses: actions/checkout@v2

      - name: Setup Conda Environment
        shell: powershell
        run: |
          # Ensure Conda is initialized. This assumes Conda has been added to PATH during runner setup.
          conda init
          # Reactivate shell to enable conda commands
          & $PROFILE

      - name: Activate Conda Environment
        shell: powershell
        run: |
          # Activate your environment. Replace `your_env_name` with your actual environment name.
          conda activate tkworkenv
          # Print the active environment to verify
          conda info