# .github/workflows/install-windows-service.yml
name: My Workflow


on:
  workflow_dispatch:

jobs:
  activate_conda:
    name: Activate Conda Environment
    runs-on: self-hosted

    steps:
      - name: Check out Repository
        uses: actions/checkout@v2


      - name: Setup, Activate Conda Environment and Install Dependencies
        shell: powershell
        run: |
          conda init powershell
          $PROFILE
          conda activate tkworkenv
          conda info
          conda info --envs
          conda install openssl pyodbc
          python -m pip install -r requirements.txt
          conda list
      
          