# .github/workflows/install-windows-service.yml
name: My Workflow


on:
  workflow_dispatch:

jobs:
  activate_conda:
    name: Activate Conda Environment
    runs-on: self-hosted

    steps:
      - name: Check out Repository
        uses: actions/checkout@v2


      - name: Setup Conda Environment
        shell: powershell
        run: |
          conda init powershell

      - name: Activate Conda Environment
        shell: powershell
        run: |
          conda activate tkworkenv
          # Print the active environment to verify
          conda info
          