# .github/workflows/stop_service.yml
name: Stop Service

on:
  workflow_dispatch:

jobs:
  stop_service:
    name: Stop service
    runs-on: self-hosted

    steps:
      - name: Stopping the service
        shell: powershell
        run: |
          Stop-Service -Name bookscraperservice
          Get-Service -Name bookscraperservice